df_raw <- read.csv("C:/Users/Lelan/Desktop/data609_project/proj_v3.csv", header = TRUE, sep = ",")
install.packages("digest")
library(digest)
df_raw$merchant_hash <- sapply(df_raw$merchant_id, digest)
df_currency <- read.csv("C:/Users/Lelan/Desktop/data609_project/proj_currency.csv", header = TRUE, sep = ",")
df_raw <- merge(df_raw, df_currency, by = "geographic_country", all = TRUE)
df_raw$per_item_rate_usd <- round(df_raw$per_item_rate * df_raw$conversion_rate, 4)
df_raw$vol_usd <- round(df_raw$vol * df_raw$conversion_rate, 2)
df_raw$rev_usd <- round(df_raw$revenue * df_raw$conversion_rate, 2)
proj_df <- subset(df_raw, select = c("geographic_country","geographic_region","lob","merchant_hash","card_brand","perc_rate","per_item_rate_usd","trans","vol_usd","rev_usd","from_currency","conversion_rate","per_item_rate","vol","revenue"))
colnames(proj_df) <- c("geographic_country","geographic_region","lob","merchant_hash","card_brand","perc_rate","per_item_rate_usd","trans","vol_usd","rev_usd","from_currency","conversion_rate","per_item_rate_lcl","vol_lcl","rev_lcl")
proj_df <- proj_df[!(is.na(proj_df$rev_usd)),]
proj_df <- proj_df[!(proj_df$perc_rate < 0),]
proj_df <- proj_df[!(proj_df$per_item_rate_lcl < 0),]
proj_df <- proj_df[!(proj_df$perc_rate >= 50),]
write.csv(proj_df, file = "C:/Users/Lelan/Desktop/data609_project/proj_df.csv")

for (i in 1:nrow(proj_df)) {
  if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Amex') {proj_df$perc_rate_ceiling[i] <- min(5.00, proj_df$perc_rate[i] * 1.1)} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Discover') {proj_df$perc_rate_ceiling[i] <- proj_df$perc_rate[i]} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.1)} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.1)} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Amex') {proj_df$perc_rate_ceiling[i] <- min(5.00, proj_df$perc_rate[i] + 0.40, proj_df$perc_rate[i] * 1.1)} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Discover') {proj_df$perc_rate_ceiling[i] <- proj_df$perc_rate[i]} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 0.40, proj_df$perc_rate[i] * 1.1)} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 0.40, proj_df$perc_rate[i] * 1.1)} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Integrated' & proj_df$card_brand[i] == 'Amex') {proj_df$perc_rate_ceiling[i] <- min(5.00, proj_df$perc_rate[i] * 1.1)} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Integrated' & proj_df$card_brand[i] == 'Discover') {proj_df$perc_rate_ceiling[i] <- proj_df$perc_rate[i]} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Integrated' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.1)} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Integrated' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.1)} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'Amex') {proj_df$perc_rate_ceiling[i] <- proj_df$perc_rate[i] + 0.02} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'Discover') {proj_df$perc_rate_ceiling[i] <- proj_df$perc_rate[i] + 0.02} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- proj_df$perc_rate[i] + 0.02} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- proj_df$perc_rate[i] + 0.02} 
  else if (proj_df$geographic_country[i] == 'Canada (USD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Discover') {proj_df$perc_rate_ceiling[i] <- proj_df$perc_rate[i]} 
  else if (proj_df$geographic_country[i] == 'Canada (USD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.1)} 
  else if (proj_df$geographic_country[i] == 'Canada (USD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.1)} 
  else if (proj_df$geographic_country[i] == 'Canada (USD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 0.40, proj_df$perc_rate[i] * 1.1)} 
  else if (proj_df$geographic_country[i] == 'Canada (USD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 0.40, proj_df$perc_rate[i] * 1.1)} 
  else if (proj_df$geographic_country[i] == 'Canada (USD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Integrated' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.1)} 
  else if (proj_df$geographic_country[i] == 'Canada (USD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Integrated' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.1)} 
  else if (proj_df$geographic_country[i] == 'Canada (USD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- proj_df$perc_rate[i] + 0.02} 
  else if (proj_df$geographic_country[i] == 'Canada (USD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- proj_df$perc_rate[i] + 0.02} 
  else if (proj_df$geographic_country[i] == 'Hong Kong' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.18)} 
  else if (proj_df$geographic_country[i] == 'Hong Kong' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.18)} 
  else if (proj_df$geographic_country[i] == 'Hong Kong' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Discover') {proj_df$perc_rate_ceiling[i] <- proj_df$perc_rate[i]} 
  else if (proj_df$geographic_country[i] == 'Hong Kong' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 0.40, proj_df$perc_rate[i] * 1.18)} 
  else if (proj_df$geographic_country[i] == 'Hong Kong' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 0.40, proj_df$perc_rate[i] * 1.18)} 
  else if (proj_df$geographic_country[i] == 'India' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.1116)} 
  else if (proj_df$geographic_country[i] == 'India' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.1116)} 
  else if (proj_df$geographic_country[i] == 'India' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 0.40, proj_df$perc_rate[i] * 1.1116)} 
  else if (proj_df$geographic_country[i] == 'India' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 0.40, proj_df$perc_rate[i] * 1.1116)} 
  else if (proj_df$geographic_country[i] == 'Macau' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.18)} 
  else if (proj_df$geographic_country[i] == 'Macau' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.18)} 
  else if (proj_df$geographic_country[i] == 'Macau' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 0.40, proj_df$perc_rate[i] * 1.18)} 
  else if (proj_df$geographic_country[i] == 'Macau' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 0.40, proj_df$perc_rate[i] * 1.18)} 
  else if (proj_df$geographic_country[i] == 'Malaysia' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.18)} 
  else if (proj_df$geographic_country[i] == 'Malaysia' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.18)} 
  else if (proj_df$geographic_country[i] == 'Malaysia' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 0.40, proj_df$perc_rate[i] * 1.18)} 
  else if (proj_df$geographic_country[i] == 'Malaysia' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 0.40, proj_df$perc_rate[i] * 1.18)} 
  else if (proj_df$geographic_country[i] == 'Maldives' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.18)} 
  else if (proj_df$geographic_country[i] == 'Maldives' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.18)} 
  else if (proj_df$geographic_country[i] == 'Maldives' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 0.40, proj_df$perc_rate[i] * 1.18)} 
  else if (proj_df$geographic_country[i] == 'Maldives' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 0.40, proj_df$perc_rate[i] * 1.18)} 
  else if (proj_df$geographic_country[i] == 'Philippines' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- proj_df$perc_rate[i]} 
  else if (proj_df$geographic_country[i] == 'Philippines' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- proj_df$perc_rate[i]} 
  else if (proj_df$geographic_country[i] == 'Philippines' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- proj_df$perc_rate[i]} 
  else if (proj_df$geographic_country[i] == 'Philippines' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- proj_df$perc_rate[i]} 
  else if (proj_df$geographic_country[i] == 'Singapore' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.15)} 
  else if (proj_df$geographic_country[i] == 'Singapore' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.15)} 
  else if (proj_df$geographic_country[i] == 'Singapore' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 0.40, proj_df$perc_rate[i] * 1.15)} 
  else if (proj_df$geographic_country[i] == 'Singapore' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 0.40, proj_df$perc_rate[i] * 1.15)} 
  else if (proj_df$geographic_country[i] == 'Sri Lanka' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.066)} 
  else if (proj_df$geographic_country[i] == 'Sri Lanka' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.066)} 
  else if (proj_df$geographic_country[i] == 'Sri Lanka' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 0.40, proj_df$perc_rate[i] * 1.066)} 
  else if (proj_df$geographic_country[i] == 'Sri Lanka' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 0.40, proj_df$perc_rate[i] * 1.066)} 
  else if (proj_df$geographic_country[i] == 'United Kingdom' & proj_df$geographic_region[i] == 'Europe' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Amex') {proj_df$perc_rate_ceiling[i] <- min(5.00, proj_df$perc_rate[i] * 1.06)} 
  else if (proj_df$geographic_country[i] == 'United Kingdom' & proj_df$geographic_region[i] == 'Europe' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.06)} 
  else if (proj_df$geographic_country[i] == 'United Kingdom' & proj_df$geographic_region[i] == 'Europe' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.06)} 
  else if (proj_df$geographic_country[i] == 'United Kingdom' & proj_df$geographic_region[i] == 'Europe' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Amex') {proj_df$perc_rate_ceiling[i] <- min(5.00, proj_df$perc_rate[i] * 1.06, proj_df$perc_rate[i] + 0.40)} 
  else if (proj_df$geographic_country[i] == 'United Kingdom' & proj_df$geographic_region[i] == 'Europe' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 0.40, proj_df$perc_rate[i] * 1.06)} 
  else if (proj_df$geographic_country[i] == 'United Kingdom' & proj_df$geographic_region[i] == 'Europe' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 0.40, proj_df$perc_rate[i] * 1.06)} 
  else if (proj_df$geographic_country[i] == 'United Kingdom' & proj_df$geographic_region[i] == 'Europe' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'Amex') {proj_df$perc_rate_ceiling[i] <- proj_df$perc_rate[i] + 0.02} 
  else if (proj_df$geographic_country[i] == 'United Kingdom' & proj_df$geographic_region[i] == 'Europe' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- proj_df$perc_rate[i] + 0.02} 
  else if (proj_df$geographic_country[i] == 'United Kingdom' & proj_df$geographic_region[i] == 'Europe' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- proj_df$perc_rate[i] + 0.02} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Amex') {proj_df$perc_rate_ceiling[i] <- min(5.00, proj_df$perc_rate[i] * 1.18)} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Discover') {proj_df$perc_rate_ceiling[i] <- proj_df$perc_rate[i]} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.18)} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.18)} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Amex') {proj_df$perc_rate_ceiling[i] <- min(5.00, proj_df$perc_rate[i] * 1.1)} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Discover') {proj_df$perc_rate_ceiling[i] <- proj_df$perc_rate[i]} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 0.40, proj_df$perc_rate[i] * 1.18)} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 0.40, proj_df$perc_rate[i] * 1.18)} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Integrated' & proj_df$card_brand[i] == 'Amex') {proj_df$perc_rate_ceiling[i] <- min(5.00, proj_df$perc_rate[i] * 1.1)} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Integrated' & proj_df$card_brand[i] == 'Discover') {proj_df$perc_rate_ceiling[i] <- proj_df$perc_rate[i]} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Integrated' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.1)} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Integrated' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- min(proj_df$perc_rate[i] + 1, proj_df$perc_rate[i] * 1.1)} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'Amex') {proj_df$perc_rate_ceiling[i] <- proj_df$perc_rate[i] + 0.02} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'Discover') {proj_df$perc_rate_ceiling[i] <- proj_df$perc_rate[i] + 0.02} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'MasterCard') {proj_df$perc_rate_ceiling[i] <- proj_df$perc_rate[i] + 0.02} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'Visa') {proj_df$perc_rate_ceiling[i] <- proj_df$perc_rate[i] + 0.02} 
}

for (i in 1:nrow(proj_df)) {
  if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Amex') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Discover') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Amex') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Discover') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Integrated' & proj_df$card_brand[i] == 'Amex') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Integrated' & proj_df$card_brand[i] == 'Discover') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Integrated' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Integrated' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'Amex') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] + 0.01} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'Discover') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] + 0.01} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] + 0.01} 
  else if (proj_df$geographic_country[i] == 'Canada (CAD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] + 0.01} 
  else if (proj_df$geographic_country[i] == 'Canada (USD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Discover') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1} 
  else if (proj_df$geographic_country[i] == 'Canada (USD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1} 
  else if (proj_df$geographic_country[i] == 'Canada (USD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1} 
  else if (proj_df$geographic_country[i] == 'Canada (USD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1} 
  else if (proj_df$geographic_country[i] == 'Canada (USD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1} 
  else if (proj_df$geographic_country[i] == 'Canada (USD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Integrated' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1} 
  else if (proj_df$geographic_country[i] == 'Canada (USD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Integrated' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1} 
  else if (proj_df$geographic_country[i] == 'Canada (USD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] + 0.01} 
  else if (proj_df$geographic_country[i] == 'Canada (USD)' & proj_df$geographic_region[i] == 'Canada' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] + 0.01} 
  else if (proj_df$geographic_country[i] == 'Hong Kong' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.18} 
  else if (proj_df$geographic_country[i] == 'Hong Kong' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.18} 
  else if (proj_df$geographic_country[i] == 'Hong Kong' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Discover') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.18} 
  else if (proj_df$geographic_country[i] == 'Hong Kong' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.18} 
  else if (proj_df$geographic_country[i] == 'Hong Kong' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.18} 
  else if (proj_df$geographic_country[i] == 'India' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1116} 
  else if (proj_df$geographic_country[i] == 'India' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1116} 
  else if (proj_df$geographic_country[i] == 'India' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1116} 
  else if (proj_df$geographic_country[i] == 'India' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1116} 
  else if (proj_df$geographic_country[i] == 'Macau' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.18} 
  else if (proj_df$geographic_country[i] == 'Macau' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.18} 
  else if (proj_df$geographic_country[i] == 'Macau' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.18} 
  else if (proj_df$geographic_country[i] == 'Macau' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.18} 
  else if (proj_df$geographic_country[i] == 'Malaysia' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.18} 
  else if (proj_df$geographic_country[i] == 'Malaysia' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.18} 
  else if (proj_df$geographic_country[i] == 'Malaysia' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.18} 
  else if (proj_df$geographic_country[i] == 'Malaysia' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.18} 
  else if (proj_df$geographic_country[i] == 'Maldives' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.18} 
  else if (proj_df$geographic_country[i] == 'Maldives' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.18} 
  else if (proj_df$geographic_country[i] == 'Maldives' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.18} 
  else if (proj_df$geographic_country[i] == 'Maldives' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.18} 
  else if (proj_df$geographic_country[i] == 'Philippines' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i]} 
  else if (proj_df$geographic_country[i] == 'Philippines' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i]} 
  else if (proj_df$geographic_country[i] == 'Philippines' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i]} 
  else if (proj_df$geographic_country[i] == 'Philippines' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i]} 
  else if (proj_df$geographic_country[i] == 'Singapore' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.15} 
  else if (proj_df$geographic_country[i] == 'Singapore' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.15} 
  else if (proj_df$geographic_country[i] == 'Singapore' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.15} 
  else if (proj_df$geographic_country[i] == 'Singapore' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.15} 
  else if (proj_df$geographic_country[i] == 'Sri Lanka' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.066} 
  else if (proj_df$geographic_country[i] == 'Sri Lanka' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.066} 
  else if (proj_df$geographic_country[i] == 'Sri Lanka' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.066} 
  else if (proj_df$geographic_country[i] == 'Sri Lanka' & proj_df$geographic_region[i] == 'Asia-Pacific' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.066} 
  else if (proj_df$geographic_country[i] == 'United Kingdom' & proj_df$geographic_region[i] == 'Europe' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Amex') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.06} 
  else if (proj_df$geographic_country[i] == 'United Kingdom' & proj_df$geographic_region[i] == 'Europe' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.06} 
  else if (proj_df$geographic_country[i] == 'United Kingdom' & proj_df$geographic_region[i] == 'Europe' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.06} 
  else if (proj_df$geographic_country[i] == 'United Kingdom' & proj_df$geographic_region[i] == 'Europe' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Amex') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.06} 
  else if (proj_df$geographic_country[i] == 'United Kingdom' & proj_df$geographic_region[i] == 'Europe' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.06} 
  else if (proj_df$geographic_country[i] == 'United Kingdom' & proj_df$geographic_region[i] == 'Europe' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.06} 
  else if (proj_df$geographic_country[i] == 'United Kingdom' & proj_df$geographic_region[i] == 'Europe' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'Amex') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] + 0.01} 
  else if (proj_df$geographic_country[i] == 'United Kingdom' & proj_df$geographic_region[i] == 'Europe' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] + 0.01} 
  else if (proj_df$geographic_country[i] == 'United Kingdom' & proj_df$geographic_region[i] == 'Europe' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] + 0.01} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Amex') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.18} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Discover') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.18} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.18} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Direct' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.18} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Amex') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Discover') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.18} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.18} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Enterprise' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.18} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Integrated' & proj_df$card_brand[i] == 'Amex') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Integrated' & proj_df$card_brand[i] == 'Discover') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.18} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Integrated' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Integrated' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] * 1.1} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'Amex') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] + 0.01} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'Discover') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] + 0.01} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'MasterCard') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] + 0.01} 
  else if (proj_df$geographic_country[i] == 'United States' & proj_df$geographic_region[i] == 'United States' & proj_df$lob[i] == 'Wholesale' & proj_df$card_brand[i] == 'Visa') {proj_df$per_item_rate_ceiling[i] <- proj_df$per_item_rate_usd[i] + 0.01} 
}

proj_df$perc_rate_ceiling <- round(proj_df$perc_rate_ceiling, 4)
proj_df$per_item_rate_ceiling <- round(proj_df$per_item_rate_ceiling, 4)
proj_df$rev_at_ceiling_usd <- round((proj_df$vol_usd * (proj_df$perc_rate_ceiling/100)) + (proj_df$trans * proj_df$per_item_rate_ceiling), 2)

proj_df2 <- subset(proj_df, select = c("geographic_region","lob","merchant_hash","card_brand","perc_rate","per_item_rate_usd","trans","vol_usd"))
proj_df2$mlob <- ifelse(as.character(proj_df2$lob) == 'Enterprise','Direct',as.character(proj_df2$lob))
proj_df2 <- subset(proj_df2, lob != 'Wholesale')
proj_df2_ttls <- sqldf("select geographic_region, lob, card_brand, sum(trans) as ttl_trans, sum(vol_usd) as ttl_vol from proj_df2 group by geographic_region, lob, card_brand order by geographic_region, lob, card_brand")
proj_df3 <- merge(proj_df2, proj_df2_ttls, by = c("geographic_region","lob","card_brand"), all = TRUE)
proj_df3$per_item_weighted <- (proj_df3$trans/proj_df3$ttl_trans) * proj_df3$per_item_rate_usd
proj_df_final <- sqldf("select geographic_region, lob, card_brand, ttl_trans as transactions, round(ttl_vol,2) as volume, round(sum(per_item_weighted),4) as per_item_rate, round(sum((vol_usd/ttl_vol) * perc_rate),4) as percentage_rate from proj_df3 group by geographic_region, lob, card_brand, ttl_trans, ttl_vol order by geographic_region, lob, card_brand")
write.csv(proj_df_final, file = "C:/Users/Lelan/Desktop/data609_project/proj_df_final.csv")

